LIB=-L/usr/local/lib
INC=-I/usr/local/include
LIBS=-lopencv_world
main:	EagleVision.cpp
	g++ EagleVision.cpp -o EagleVision -I/usr/local/include -L/usr/local/lib -lopencv_world
clean:
	-rm -f EagleVision.o
	-rm -f EagleVision
